<?php
// Configuration for visible tables
$visibleTables = [
    'emp_ctcdetails_info',
    'emp_personal_info',
    'generate_urn3'
    
];

// Table aliases
$tableAliases = [
    'emp_ctcdetails_info' => 'Employee CTC Details',
    'emp_personal_info' => 'Employee Personal Info',
    'generate_urn3' => 'Document Generation'
];

// Column aliases
$columnAliases = [
    // emp_ctcdetails_info columns
    'emp_ctcdetails_info' => [
        'indo_code' => 'Employee Code',
        'stateName' => 'State',
        'category' => 'Category',
        'skill_status' => 'Skill Status',
        'basic' => 'Basic Salary',
        'daily_allowance' => 'Daily Allowance',
        'hra' => 'HRA',
        'laptopOwner' => 'Laptop Owner',
        'laptopRent' => 'Laptop Rent',
        'lapSecurityIns' => 'Laptop Security Insurance',
        'lapSecurityTotalAmt' => 'Laptop Security Total Amount',
        'lapsecurityDedcution' => 'Laptop Security Deduction',
        'tkOwner' => 'TK Owner',
        'tkRent' => 'TK Rent',
        'tkSecurityIns' => 'TK Security Insurance',
        'tkSecurityTotalAmt' => 'TK Security Total Amount',
        'tksecurityDedcution' => 'TK Security Deduction',
        'sktOwner' => 'SKT Owner',
        'sktRent' => 'SKT Rent',
        'sktSecurityIns' => 'SKT Security Insurance',
        'sktSecurityTotalAmt' => 'SKT Security Total Amount',
        'sktsecurityDedcution' => 'SKT Security Deduction',
        'mobileOwner' => 'Mobile Owner',
        'mobileRent' => 'Mobile Rent',
        'mobileSecurityIns' => 'Mobile Security Insurance',
        'mobileSecurityTotalAmt' => 'Mobile Security Total Amount',
        'mobilesecurityDedcution' => 'Mobile Security Deduction',
        'conveyance_allowance' => 'Conveyance Allowance',
        'books_periodicals' => 'Books & Periodicals',
        'washing_allowance' => 'Washing Allowance',
        'food_allowance' => 'Food Allowance',
        'transportation_charges' => 'Transportation Charges',
        'vehicle_remb' => 'Vehicle Reimbursement',
        'other_allowance' => 'Other Allowance',
        'bonus' => 'Bonus',
        'attendance_bonus' => 'Attendance Bonus',
        'cityCompensatoryAllowance' => 'City Compensatory Allowance',
        'medical_allowance' => 'Medical Allowance',
        'mobile_allowance' => 'Mobile Allowance',
        'Lta' => 'LTA',
        'specialAllowance' => 'Special Allowance',
        'lwa' => 'LWA',
        'gross_salary' => 'Gross Salary',
        'lwf' => 'LWF',
        'ESIC' => 'ESIC',
        'mediclaim' => 'Mediclaim',
        'canteen' => 'Canteen',
        'uniform' => 'Uniform',
        'emp_provident_fund' => 'Employee Provident Fund',
        'PF_flag' => 'PF Flag',
        'professional_tax' => 'Professional Tax',
        'transaction_charge' => 'Transaction Charge',
        'tds' => 'TDS',
        'other_deduction' => 'Other Deduction',
        'admin_charges' => 'Admin Charges',
        'netSalary' => 'Net Salary',
        'employer_ESIC' => 'Employer ESIC',
        'employer_lwf' => 'Employer LWF',
        'employer_providentFund' => 'Employer Provident Fund',
        'leave_encashment' => 'Leave Encashment',
        'gratuity' => 'Gratuity',
        'annual_bonus' => 'Annual Bonus',
        'yearly_variable' => 'Yearly Variable',
        'monthly_ctc' => 'Monthly CTC',
        'poValue' => 'PO Value',
        'remarks' => 'Remarks',
        'increment_applicable_from' => 'Increment Applicable From',
        'status' => 'Status',
        'offeredBy' => 'Offered By',
        'offeredDate' => 'Offered Date',
        'confirmedBy' => 'Confirmed By',
        'confirmedDate' => 'Confirmed Date',
        'lastUpdate' => 'Last Update',
        'lastUpdatedBy' => 'Last Updated By'
    ],
    
    // emp_personal_info columns
    'emp_personal_info' => [
        'emp_id' => 'Employee ID',
        'indo_code' => 'Employee Code',
        'rom_empcode' => 'ROM Employee Code',
        'old_indocode' => 'Old Employee Code',
        'empl_id' => 'Employee ID',
        'reg_id' => 'Registration ID',
        'agencyid' => 'Agency ID',
        'companyName' => 'Company Name',
        'working_shift_id' => 'Working Shift',
        'verticalName' => 'Vertical',
        'empType' => 'Employee Type',
        'position_code' => 'Position Code',
        'new_code' => 'New Code',
        'resource_name' => 'Employee Name',
        'gender' => 'Gender',
        'dob' => 'Date of Birth',
        'designation' => 'Designation',
        'positionRole' => 'Position Role',
        'department' => 'Department',
        'prime_department' => 'Prime Department',
        'national_circle' => 'National Circle',
        'circle_name' => 'Circle Name',
        'city_name' => 'City',
        'pincode' => 'Pincode',
        'base_location' => 'Base Location',
        'offered_date' => 'Offered Date',
        'offered_by' => 'Offered By',
        'expected_joining_date' => 'Expected Joining Date',
        'joining_date' => 'Joining Date',
        'contract_probation_days' => 'Probation Days',
        'contract_probation_completed' => 'Probation Completed',
        'old_joiningdate' => 'Old Joining Date',
        'mobile_number' => 'Mobile Number',
        'email_id' => 'Email',
        'official_email_id' => 'Official Email',
        'married_status' => 'Marital Status',
        'fatherName' => 'Father Name',
        'esic_number' => 'ESIC Number',
        'pf_number' => 'PF Number',
        'uan_number' => 'UAN Number',
        'pancard' => 'PAN Card',
        'pancard_number' => 'PAN Number',
        'aadharcard' => 'Aadhar Card',
        'passport' => 'Passport',
        'passport_back' => 'Passport Back',
        'mediclaimdoc' => 'Mediclaim Document',
        'esicdoc' => 'ESIC Document',
        'aadhar_number' => 'Aadhar Number',
        'permanent_address' => 'Permanent Address',
        'current_address' => 'Current Address',
        'photo' => 'Photo',
        'blood_group' => 'Blood Group',
        'pledgedoc' => 'Pledge Document',
        'another_mobile' => 'Alternate Mobile',
        'reportingMgrName' => 'Reporting Manager',
        'reportingMgrContact' => 'Manager Contact',
        'reportingMgrEmail' => 'Manager Email',
        'description' => 'Description',
        'infoCompleted' => 'Info Completed',
        'punchType' => 'Punch Type',
        'remark' => 'Remark',
        'updateDatesAr' => 'Update Dates',
        'updateUsersAr' => 'Update Users',
        'lastUpdate' => 'Last Update',
        'lastUpdatedBy' => 'Last Updated By',
        'geo_tracking_status' => 'Geo Tracking',
        'office_location_id' => 'Office Location',
        'working_location_id' => 'Working Location',
        'working_location_address' => 'Work Location Address',
        'contact_person_name' => 'Contact Person',
        'contact_person_email' => 'Contact Email',
        'contact_person_mobile' => 'Contact Mobile',
        'terms_condition' => 'Terms & Conditions'
    ],
    
    // generate_urn3 columns
    'generate_urn3' => [
        'id' => 'ID',
        'company_id' => 'Company',
        'department_id' => 'Department',
        'reference_number' => 'Reference Number',
        'approver_status' => 'Approver Status',
        'third_party_approver_status' => 'Third Party Status',
        'document_locked_status' => 'Document Locked',
        'year' => 'Year',
        'project_code' => 'Project Code',
        'document_name' => 'Document Name',
        'purpose' => 'Purpose',
        'approver_name' => 'Approver Name',
        'third_party_approver_name' => 'Third Party Approver',
        'third_party_approver_id' => 'Third Party Approver ID',
        'approver_type' => 'Approver Type',
        'approver_code' => 'Approver Code',
        'output_type_id' => 'Output Type',
        'remarks' => 'Remarks',
        'third_party_remarks' => 'Third Party Remarks',
        'emp_code' => 'Employee Code',
        'emp_name' => 'Employee Name',
        'document_type' => 'Document Type',
        'create_datetime' => 'Created On',
        'third_party_action_date' => 'Third Party Action Date',
        'created_by' => 'Created By',
        'action_by' => 'Action By',
        'action_date' => 'Action Date',
        'status' => 'Status'
    ]
];